### ISSUE TITLE
Whitelist is not a whitelist

### ISSUE THREAD

**Issue by biker-ruud** [gary-rowe/BitcoinjEnforcerRules#4]
A whitelist should block all, unless present on list.
As a blacklist should allow all, unless present on list.

If a dependency is missing from the list, the DigestRule does not break the build.
Large projects have lots of depenencies. 
Forgetting to add one to the list creates security risks, as these are not checked for valid signatures.

**Comment by schildbach** [comment]
I think this is a dupe of #1

**Comment by gary-rowe** [comment]
Agreed. Closing this as duplicate.
